# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godot
    - gofumpt
    - gosec
    - noctx
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/pp/lnk
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
